events { }
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        root /usr/share/nginx/html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Явно указываем MIME-тип для файлов фреймворка
        location ~ ^/_framework/ {
            gzip_static on; # Nginx будет отдавать .gz файлы, если они есть
            types {
                application/javascript js;
                application/wasm wasm;
            }
            try_files $uri =404;
        }
    }
}
