events { }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Явное указание типов для корректной работы Blazor
    types {
        application/wasm               wasm;
        application/octet-stream      dll;
        application/octet-stream      pdb;
        application/javascript        js;
        application/json              json;
    }

    server {
        listen 80;
        root /usr/share/nginx/html;

        # Раздача статики фронтенда
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Проксирование запросов к API
        # Теперь фронт будет стучаться на /api, а Nginx перекинет это в контейнер бэкенда
        location /api/ {
            proxy_pass http://api:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Настройки для системных файлов Blazor
        location /_framework/ {
            gzip_static on;
            try_files $uri =404;
        }
    }
}
