events { }
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        root /usr/share/nginx/html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Просто разрешаем отдавать файлы из _framework
        location /_framework/ {
            gzip_static on;
            try_files $uri =404;
        }
    }
}
